### PR TITLE
Reduce deprecation warnings

### PR DESCRIPTION
**Pull request by ssoper**
https://github.com/tidwall/Safe/issues/4

### CODE REVIEW

**Comment by tidwall** [comment]
Actually removing these operations will most likely break compatibility. Perhaps this is another case for warning suppression. 

Thoughts?

**Comment by ssoper** [comment]
Swift 3 isn't due out til 2017 so it'll buy you a year :moneybag:

**Comment by ssoper** [comment]
Doesn't look like there's a way to suppress in Swift like there was in ObjC with `#pragma`
http://stackoverflow.com/questions/28357297/swift-alternative-for-pragma-clang-diagnostic

I dug around in swift source and was able to find some defines but they don’t seem to be exposed when compiling swift files.
https://github.com/apple/swift/blob/14a3ab61cbccdb64fcf3e32da31e97321b73ebfd/CMakeLists.txt

So this doesn't work

``` swift
#if SWIFT_VERSION
print(SWIFT_VERSION)
#else
print("doesnt work")
#endif
```

Perhaps you could create a separate branch called 'Linux' which will have these deprecation warnings fixed but otherwise be the same. You could also continue with the `v` naming scheme on the main branch while Linux remove the 'v'.

**Comment by ssoper** [comment]
If the `atomic.swift` file is auto-generated perhaps it could be built with a Makefile that greps the output of `swift --version` and then builds the appropriate version.

``` bash
USE_GENERATOR=$(swift --version | grep -q 2.1 && echo "v2.1-gen.sh" || echo "v2.2-gen.sh")
```

**Pull request merged**
